[package]
name = "kmeans-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.12.0"
ndarray-rand = "0.9.0"
ndarray-parallel = "0.9.0"
rand = "0.6.0"
statrs = "0.9.0"

